services:
  app:
    container_name: muzer-docker
    build:
      context: ./muzer
      dockerfile: Dockerfile.dev
    env_file:
      - ./muzer/.env
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./muzer:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    container_name: prisma-postgres
    image: postgres:alpine
    restart: always
    env_file:
      - ./muzer/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  websockets:
    container_name: websockets
    restart: always
    build:
      context: .
      dockerfile: ws/Dockerfile.dev
      args:
        DATABASE_URL: "postgresql://neondb_owner:npg_rxguqZR3Pk4O@ep-misty-bush-a86dxyz7-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
    env_file:
      - ./ws/.env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
     DATABASE_URL: "postgresql://neondb_owner:npg_rxguqZR3Pk4O@ep-misty-bush-a86dxyz7-pooler.eastus2.azure.neon.tech/neondb?sslmode=require"
    volumes:
      - ./ws:/usr/src/app
      - ./muzer/lib:/usr/src/app/muzer/lib   # ✅ Add this to mount just the lib
      - /usr/src/app/node_modules

volumes:
  postgres-data:
    external: false