FROM node:22-alpine AS installer

WORKDIR /usr/src/app
RUN corepack enable npm
COPY package.json npm-lock.yaml ./
RUN npm install --frozen-lockfile --ignore-scripts
COPY . .
RUN npm run postinstall


FROM node:22-alpine AS dev

WORKDIR /usr/src/app
RUN corepack enable npm
COPY --from=installer /usr/src/app/ ./
CMD [ "npm","run", "dev" ]

